name: maintain-please-backport-action
description: Automated backport pull requests creation
author: tsuhama

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: skip-back
  color: red

# Define your inputs here.
inputs:
  milliseconds:
    description: Your input description here
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: Your output description here

runs:
  using: node20
  main: ../dist/backport/index.js
