# This workflow checks the statuses of cached dependencies used in this action
# with the help of the Licensed tool. If any licenses are invalid or missing,
# this workflow will fail. See: https://github.com/licensee/licensed

name: Licensed

on:
  push:

permissions:
  contents: write

jobs:
  licensed:
    name: Check Licenses
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: NPM Login
        id: npm-login
        run:
          npm set
          "//npm.pkg.github.com/:_authToken=${{secrets.NPM_REGISTRY_GITHUB_TOKEN}}"

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Setup Ruby
        id: setup-ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby

      - uses: licensee/setup-licensed@v1.3.2
        with:
          version: 4.x

      - name: Check Licenses
        id: check-licenses
        run: licensed status
